site_name: Leapp - Docs
site_url: https://docs.leapp.cloud/
repo_url: https://github.com/Noovolari/leapp
site_description: 'Leapp is a tool for developers to manage, secure, and access the cloud. Manage AWS and Azure credentials centrally'
copyright: '© 2021 Noovolari, All rights reserved. | Powered by beSharp'

nav:
  - 'Get Started':
      - Intro: index.md
      - Installation:
          - 'Pre-install': 'installation/pre-install.md'
          - 'Installing Leapp': 'installation/installing-leapp.md'
          - 'Updating Leapp': 'installation/updating-leapp.md'
      - Sessions: 'sessions.md'
      - Integrations: 'integrations.md'
  - 'Configuring Session':
      - 'Configure AWS IAM User': 'configuring-session/configure-aws-iam-user.md'
      - 'Configure AWS IAM Role Federated': 'configuring-session/configure-aws-iam-role-federated.md'
      - 'Configure AWS IAM Role Chained': 'configuring-session/configure-aws-iam-role-chained.md'
      - 'Configure Azure Tenant': 'configuring-session/configure-azure-tenant.md'
  - 'Configuring Integration':
      - 'Configure AWS Single Sign-On integration': 'configuring-integration/configure-aws-single-sign-on-integration.md'
  - Security:
      - 'Credentials generation':
          - AWS: 'security/credentials-generation/aws.md'
          - Azure: 'security/credentials-generation/azure.md'
      - Keychain: 'security/keychain.md'
  - 'Built-in features':
      - 'EC2 connector through AWS System manager': 'built-in-features/ec2-connector-through-aws-system-manager.md'
      - 'Proxy Server': 'built-in-features/proxy-server.md'
      - 'Multi-profile management': 'built-in-features/multi-profile-management.md'
  - Contributing:
      - 'Get involved': 'contributing/get-involved.md'
      - 'Project structure': 'contributing/project-structure.md'

theme:
  logo: images/logo.png
  titles_only: true
  favicon: images/favicon.ico
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  font:
    text: Lato
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocs-video
  - img2fig

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-FB1NX90MYZ
  consent:
    cookies:
      analytics: Google Analytics
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
