name: Leapp Desktop App CD test

on:
  push:
    branches:
      - azure-msal-spike

env:
  S3_BUCKET: s3://noovolari-leapp-website-distribution
  WIN_CERTIFICATE: ${{ secrets.WIN_CERTIFICATE }}
  WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022 ]
        node_version: [ 16 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare GIT
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Set pro environment
        shell: bash
        run: npm run set-pro-environment
      - name: compress
        run: powershell Compress-Archive dpapi-addon test.zip
      - name: decompress
        run: powershell expand-archive test.zip test
      - name: ls root
        run: ls -R test
